export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS'
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL';

export const TASK_ADD_SUCCESS_CLEAR = 'TASK_ADD_SUCCESS_CLEAR'
export const TASK_ADD_FAIL_CLEAR = 'TASK_ADD_FAIL_CLEAR';

export const TASK_GET_SUCCESS = 'TASK_GET_SUCCESS';

export const GET_SINGLE_TASK ='GET_SINGLE_TASK'
export const GET_SUGGESTED_TASK = 'GET_SUGGESTED_TASK'

export const TASK_DELETE_SUCCESS ='TASK_DELETE_SUCCESS'

export const TASK_UPDATE_SUCCESS ='TASK_UPDATE_SUCCESS'