export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL ='USER_CREATE_FAIL'

export const USER_CREATE_SUCCESS_CLEAR = 'USER_CREATE_SUCCESS_CLEAR'
export const USER_CREATE_FAIL_CLEAR = 'USER_CREATE_FAIL_CLEAR'

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAIL = 'USER_GET_FAIL'

export const USER_GET_SUCCESS_CLEAR = 'USER_GET_SUCCESS_CLEAR'
export const USER_GET_FAIL_CLEAR = 'USER_GET_FAIL_CLEAR'